### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by MWFWeb** [CodyHouse/cd-morphing-image-modal-changelog#1]
Following the instructions, I downloaded and added my own images but it seems broken. The overlay appears and nothing else is shown. 

<img width="1244" alt="Screenshot 2021-01-13 at 11 45 40 AM" src="https://user-images.githubusercontent.com/18727733/104482546-0bb79200-5595-11eb-8f4f-0956d865bc8b.png">

**Comment by sebastiano-guerriero** [comment]
It seems to be missing the image extensions (e.g., .jpg)

**Comment by claudia-romano** [comment]
Closing this as no additional info was provided. Feel free to reopen it if you are still experiencing this issue. Cheers!
